language: node_js
branches:
  only:
    - master
node_js:
  - "node"
before_install:
  - npm install
script: gulp all
cache:
  directories:
    - "node_modules"
before_deploy:
  - sed -i '/dist\//d' .gitignore
  - sed -i '/index.html/d' .gitignore
  - echo 'src/' >> .gitignore
  - echo 'package.json' >> .gitignore
  - echo 'Gulpfile.js' >> .gitignore
  - curl 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js' > dist/js/jquery.min.js
  - curl 'https://cdnjs.cloudflare.com/ajax/libs/fastclick/1.0.6/fastclick.min.js' > dist/js/fastclick.min.js
  - curl 'https://cdnjs.cloudflare.com/ajax/libs/jquery.touchswipe/1.6.18/jquery.touchSwipe.min.js' > dist/js/touchswipe.min.js
  - curl 'https://cdnjs.cloudflare.com/ajax/libs/webfont/1.6.28/webfontloader.js' > dist/js/webfontloader.min.js
  - curl 'https://cdnjs.cloudflare.com/ajax/libs/suncalc/1.8.0/suncalc.min.js' > dist/js/suncalc.min.js
  - sed -i '$ d' dist/js/suncalc.min.js
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master
