language: node_js
branches:
  only:
    - master
    - /^greenkeeper\/.*$/
node_js:
  - "node"
script: gulp all
cache:
  directories:
    - "node_modules"
before_deploy:
  - sed -i '/dist\//d' .gitignore
  - sed -i '/index.html/d' .gitignore
  - sed -i '/sw.js/d' .gitignore
  - echo 'src/' >> .gitignore
  - echo 'package.json' >> .gitignore
  - echo 'Gulpfile.js' >> .gitignore
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  on:
    all_branches: true
